import Header from "../components/Header";
import Footer from "../components/Footer";
import SubheaderWhite from "../components/SubheaderWhite";
import Cardsection from "../components/Cardsection";
import ImagenPrueba from "../public/img/card-img.png";
import ImagenPrueba2 from "../public/img/card-historia.png";
import ImagenPrueba3 from "../public/img/card-fotografias.png";
import ImagenPrueba4 from "../public/img/card-creditos.png";
import React, { useEffect } from 'react'
import styles from "../styles/Historia.module.css"
import AOS from 'aos'

import 'aos/dist/aos.css'

export default function Historia(){
    useEffect(() => {
        // here you can add your aos options
        AOS.init({
          offset: 100,
        });
      }, []);
    return(
        <div className={styles.rwHistory}>
            <Header dark={false} fixed={true} />
            <div>
                <SubheaderWhite
                    scroll={true}
                    button={true}
                    imagen="/img/historia-subheader.png"
                    title="Ante la luz pública"
                    subtitle="Las fotografías del Pacífico colombiano de Robert C. West"
                    desc={<div>
                        <p>
                            <strong>Texto escrito con base en la charla dada en varias de las sedes culturales del Banco de la República, en los años 2013 y 2014, en apoyo a la exposición itinerante Comunidades del Agua, compuesta por una selección de las fotografías de Robert C. West.<br></br>
                            <span><b>Claudia Leal</b></span></strong>
                        </p>
                        <p>Las fotografías que recoge esta página hacen el milagro de transportarnos al Pacífico colombiano en la década de 1950. Para que ellas nos permitan viajar en el tiempo tuvieron que pasar varias décadas. Sin ese paso de los años, las fotografías solo lograrían salvar el espacio, lo que ya no es considerado milagroso, dado que las actuales tecnologías de comunicación nos permiten ver y escuchar continuamente lo que sucede en lugares remotos. Sumergirnos en el pasado es otro asunto –y más en el caso del Pacífico. De esta región hay pocas fotos y menos aún colecciones enteras que, como esta, nos lleven a una gran variedad de lugares y nos muestren infinidad de aspectos del ambiente y la vida material de un tiempo del que ya muy pocos tienen memoria.</p>
                        <p>El paso del tiempo no es la única condición necesaria para que este milagro sea posible; hay otro aspecto que por obvio solemos pasar por alto: la posibilidad de ver las fotografías. Ellas, como cualquier otras, son objetos físicos, y ahora también virtuales, que tienen historia. Esa historia incluye momentos y formatos en que pueden ser apreciadas y otros en los que permanecen en la sombra, como en un letargo del que pueden despertar o no. Estas fotografías en particular reposaron durante la mayoría de su existencia en el cajón de un escritorio. Allí no importaba que revelaran el sencillo encanto de una casa construida en madera o la alegría de una fiesta popular; en la medida en que prácticamente nadie las podía ver, era casi como si no existieran.</p>
                        <p>Es la vida pública de las fotografías la que las llena de significado. (Bueno, saber de un tesoro escondido también puede hacerlo, pero ese no es nuestro caso). Los medios que permiten que sean observadas y los contextos en que ello sucede moldean la forma en que se mira e interpreta lo que muestran. No es lo mismo ver fotos en un álbum familiar que en una galería de arte, la forma en que nos aproximamos a ellas cambia radicalmente. Por eso, para entender los múltiples significados de las fotografías que Robert C. West tomó en el Pacífico colombiano es pertinente reconstruir su trayectoria. Empiezo entonces por ahí y luego sí me detengo a analizar las imágenes. Para ello me enfoco en la forma en que la gente aparece retratada y termino por analizar la idea de región que resulta de este quijotesco esfuerzo. La mirada distante pero respetuosa de West era algo anacrónica: se enmarcaba dentro de una tradición larga, pero desprestigiada, de identificar tipos raciales y valoraba las formas en que las poblaciones rurales moldeaban el ambiente, sin abogar por transformaciones radicales en nombre de un esquivo ideal de desarrollo.</p>
                        <br></br>
                        <h3>Metamorfosis</h3>
                        <p>Estas fotografías me han acompañado por más de dos décadas, así que soy parte de su historia y ellas de la mía. Llegaron a mis manos por una confluencia de factores tal vez menos fortuitos de lo que parecen. En 1993, después de graduarme de la universidad, entré a trabajar en el Proyecto Biopacífico, que tenía la misión de formular una estrategia de conservación de la biodiversidad en el Pacífico colombiano. Hacía pocos meses se había aprobado la Ley 70 de 1993, que reconoce los derechos territoriales de las poblaciones negras del litoral Pacífico (que hasta ese momento vivían en baldíos de la nación). De la mano de la iglesia y de instituciones estatales como el Instituto Geográfico Agustín Codazzi, IGAC, y el Instituto Colombiano de Antropología e Historia, ICANH, se estaban formando organizaciones en los ríos de la región con miras a hacer efectiva la titulación de territorios colectivos. A quienes trabajamos allí en esos años nos inspiraba la idea de que las poblaciones rurales del litoral tenían una cultura valiosa, que era parte del alma pluriétnica y multicultural de la nación que definió la Constitución de 1991. Y a muchos también nos motivaba pensar que de la mano de esas comunidades afrodescendientes e indígenas se podría garantizar la conservación de las selvas que cubren a esa región.</p>

                        <strong>Foto</strong>

                        <p>En ese contexto de gran entusiasmo empezó a circular, si mal no recuerdo en versión fotocopiada, The Pacific Lowlands of Colombia, un libro casi olvidado, escrito por Robert C. West y publicado en 1957. Se trata de un estudio regional inspirado en los preceptos de la llamada Escuela de Berkeley. Con este nombre se conoce a un grupo de geógrafos formados por Carl O. Sauer, profesor del departamento de geografía de la Universidad de California en Berkeley entre 1923 y 1957. Sauer propuso la idea de estudiar “paisajes culturales”: la forma en que diferentes culturas transforman los paisajes naturales al vivir en ellos. En el caso del estudio de West se trataba de la “cultura negra” asentada en el litoral Pacífico que se extiende desde el sur de Panamá hasta el norte del Ecuador (ver el texto “Robert C. West y la escuela de Berkeley”, en esta página).</p>
                        <p>Desde su publicación, 30 años atrás, este libro había recibido muy poca atención en Colombia, razón por la cual nunca fue traducido. A mediados de la década de 1990, en el nuevo contexto de interés por el Pacífico, surgió la idea de publicarlo en español. Eduardo Restrepo, antropólogo y estudioso de la región, le presentó la idea al ICANH, institución que aprobó el proyecto; el Banco de la República proveyó los fondos para la traducción, que quedó a mi cargo. Pronto caímos en cuenta de un “pequeño” problema para nuestro proyecto. De las 253 páginas que tiene el libro, 50 son exclusivamente de fotografías; son 113 imágenes en total, que constituyen, junto con las 26 páginas de mapas, prueba de la importancia que West otorgaba a la información visual. Sin las fotografías no habría un nuevo libro, pero la calidad con la que aparecen reproducidas en el original es tan regular que hacía imposible utilizarlas. Teníamos que encontrar los negativos. </p>
                        <p>Para ese momento yo vivía en California, donde estaba haciendo un doctorado; allí había tenido la suerte de conocer dos años antes al profesor West, quien estuvo de visita para asistir a una reunión de celebración de la vida de su colega James Parsons, fallecido poco antes. Llamé a la Universidad de Luisiana en Baton Rouge, donde el profesor West trabajó durante varias décadas, para preguntar por él. Así me enteré que su estado de salud era precario y no podía atenderme. El director del departamento de Geografía y Antropología, William Davidson, me invitó a ir a buscar las fotografías. Unos meses después encontré, en un cajón de la oficina del profesor West, cerca de 2.000 negativos del Pacífico colombiano y un sinnúmero de copias en papel. El profesor Davidson, que era tal vez el amigo más cercano de “Bob” West, decidió encomendarme ese hallazgo. Algunas de las fotografías que West tomó en México estaban en la biblioteca, ya organizadas y disponibles para los posibles interesados, pero estas no tenían doliente y Davidson percibió una oportunidad que no iba a desperdiciar. Después de identificar y escanear las que correspondían al libro, guardé este tesoro, primero en un closet en Berkeley y luego en Bogotá.</p>
                        <p>Unos años después, entre 2007 y 2009, cuando yo ya era profesora de la Universidad de los Andes, algunos estudiantes y yo organizamos el archivo, que luego doné a la Biblioteca Luis Angel Arango. Además, creamos una página con las mejores 312 fotografías, organizadas según los criterios del propio West. Esa página desapareció a principios de 2021, cuando Adobe Flash, el programa en que estaba hecho, dejó de funcionar. Tras un largo proceso y con la ayuda del Banco de Archivos Digitales de Artes en Colombia, BADAC, montamos esta nueva versión, adaptada para ser consultada desde teléfonos celulares inteligentes, una tecnología que apenas tomaba vuelo cuando creamos la primera página. </p>
                        <p>Esta página es entonces el último engranaje de una historia que comenzó mucho antes de que las fotografías cayeran en mis manos. Son 70 años (o casi) que podemos dividir en cuatro periodos asociados a diferentes formas de vida pública, que han permitido que distintos observadores hagan lecturas diversas de estas imágenes, en tiempos cambiantes y lugares variados. Todo comenzó en 1951 con el primer viaje del profesor West al Pacífico.</p>
                        <p>En ese viaje y los siguientes, que terminaron en 1955 y fueron hechos durante los meses de verano del hemisferio norte, West tomó las fotos. Ese es entonces el periodo de creación, en el que el autor estaba inmerso en su estudio del paisaje cultural de la costa pacífica colombiana. Aunque visitó los archivos de Sevilla, Bogotá, Popayán y Quito, el grueso de su trabajo, al mejor estilo de la vieja geografía, consistió en recorrer la región. En sus viajes por aquellas selvas súper húmedas cargaba con dos cámaras: una de formato pequeño (de rollos con negativos de 35mm) y otra de formato medio (con negativos individuales de 5.5 x 5.5 cm), más pesada y costosa, pero que tomaba fotos con mayor resolución. El uso continuo de estas dos cámaras es muestra de la importancia que West le daba a la fotografía; no se trataba de un capricho o un gusto, era una parte sustancial de su trabajo. </p>

                        <strong>Foto</strong>

                        <p>Para poder usar las fotografías, West necesitaba verlas. Por eso, a medida que iba regresando de sus viajes, fue llevando los rollos y los negativos sueltos a su estudio fotográfico preferido para que fueran revelados. Luego escribió en sus respectivos sobres o tarritos dónde tomó cada uno. En la foto que hay arriba aparece el tarrito en que estaba el rollo que West tomó en el río Chagüí en la ensenada de Tumaco. Con los rótulos y el proceso de revelado las fotografías fueron emergiendo y afinando su significado: eran acetatos de celulosa, en los que era bien difícil apreciar las imágenes, pero tenían el potencial de ser utilizados para imprimir en positivo y emerger como imágenes en blanco y negro que remitirían a lugares concretos de ese largo litoral. West no tomó diapositivas, que tienen la magia del color, tal vez porque esa tecnología apenas estaba empezando a hacerse popular y porque en últimas su interés era dar a conocer sus hallazgos en papel, en publicaciones académicas que invariablemente usaban blanco y negro. Pronto mandó a imprimir muchas de las fotografías, en tamaño pequeño y papel brillante, y tomó nota de qué representaban. En ese proceso, el propio fotógrafo fue el único que observó sus fotografías; bueno, tal vez los empleados del estudio las miraron con alguna curiosidad. West les dio vida a las imágenes, no solo enfocando su lente y oprimiendo el obturador, sino mirando luego los resultados, etiquetando las fotos, y escogiendo unas pocas para que vieran la luz pública y relegando las demás al olvido.</p>
                        <p>Tras la creación y organización preliminar de las fotografías, inició el segundo y más largo periodo de esta historia, que se extiende por más de cuatro décadas, desde 1956 hasta 1999. Mientras escribía el libro, West terminó de seleccionar las 113 imágenes que hicieron parte de esta publicación de 1957. También usó algunas en su artículo sobre manglares publicado en la revista Annals of the American Association of Geographers, en 1956. La selección que resultó impresa y reproducida algunos cientos de veces era numerosa, pero apenas representaba algo más de 5% de todas las fotografías. Solo las seleccionadas tuvieron vida pública, el resto, es decir, la gran mayoría, quedó archivada en un cajón al que solo tenía acceso su autor. </p>

                        <strong>Foto</strong>

                        <p>Aunque relativamente pocas, las fotos que aparecieron en esas dos publicaciones estaban entre las más representativas de lo que a West le interesaba mostrar. Académicos, especialmente geógrafos gringos, estudiantes y colegas del profesor West, pudieron apreciar esta selección en las páginas de la revista y sobre todo del libro. Algunos especialistas en Colombia, como la antropóloga Virginia Gutiérrez de Pineda, que escribió una reseña del libro, también conocieron esta obra y sus imágenes. Allí las fotografías aparecen organizadas en hojas temáticas intercaladas con el texto, es decir, como parte integral de la investigación, no como un anexo que se puede consultar o ignorar. Sin embargo, la calidad del papel y el tamaño pequeño en que aparecen hace que pierdan parte de su gracia. Tal vez West y los editores no consideraron que éste fuera un problema crucial. Dados los costos de impresión y el pequeñísimo mercado que tendría la obra, era mejor asegurar la inclusión de la muestra completa. Además, el valor fundamental de las fotos era científico y radicaba en su capacidad para mostrar los elementos característicos del paisaje cultural del Pacífico colombiano. Ese valor dependía de que las imágenes estuvieran acompañadas de una explicación: tanto los detallados pies de foto, como el texto general del libro y del artículo. Las palabras guiaban la mirada y esa guía, por ejemplo, no tenía indicación alguna sobre cómo detallar la belleza de las imágenes. El formato entonces definía quién accedía a estas fotos y acentuaba los sesgos con los que ese público se aproximaba a ellas.</p>
                        <p>Con el paso de los años el libro debió haber quedado en el olvido; era un ejemplo de una forma de hacer geografía que examinaba una región que poco o nada le importaba a los lectores anglófonos. Pero estaba en las bibliotecas de muchas universidades y allí tal vez alguien, de vez en cuando, tuvo motivo para consultarlo. Su rescate en Colombia en la década de 1990 debió haber tenido muy poco que ver con las fotografías. Como mencioné arriba, el libro circuló en fotocopias y, por ello, las imágenes debieron haberse visto como manchas apenas discernibles.</p>

                        <strong>Foto</strong>

                        <p>Con el nuevo siglo inició un tercer periodo que va hasta 2008, en el que el libro en español –<i>Las tierras bajas del Pacífico colombiano</i>, que salió a finales de 2000– le infundió nueva vida a las fotografías: permitió que fueran vistas por un público colombiano en una versión mucho mejor en términos de papel, diseño y en muchos casos también tamaño. El libro fue vendido a un precio razonable, muy por debajo de su costo de producción, y se agotó. Sin duda, circuló más fuera de la región que dentro de ella, pero fue enviado a las bibliotecas de los principales centros urbanos del Pacífico.  </p>
                        <p>El interés por este libro escrito en los años 50 debe entenderse con relación al momento histórico del que tuve la suerte de hacer parte: el auge de los estudios sobre el Pacífico asociado a la Constitución de 1991 y la Ley 70 de 1993. Dicha ley definió a las comunidades negras ribereñas del Pacífico como un grupo étnico y determinó el proceso que debían seguir para obtener títulos colectivos de las áreas donde vivían hacía décadas e incluso algo más de dos siglos. En este contexto las fotos, y también el libro, tuvieron un cambio de significado: dejaron de ser ante todo parte de un ejercicio de la academia anglosajona para convertirse en una muestra, casi una prueba, del carácter multicultural de la nación colombiana. Gracias al paso del tiempo, las fotografías también se transformaron en vestigios del pasado, en evidencia de cómo había sido la región. Curiosamente, en esa mirada del Pacífico como región étnica, tanto de comunidades negras como de grupos indígenas, se funden pasado y presente. La idea de que la región es el territorio ancestral de dichos grupos le imprime al pasado la clave para entender el presente. La investigación recogida en el libro de West fue interpretada como evidencia de una larga ocupación y del complejo manejo del medio de las poblaciones locales, ambos aspectos cruciales de la identidad étnica. </p>
                        <p>Curiosamente, el libro también tuvo un reencauche académico, pero de poca relevancia. Su publicación en español y en Colombia permitió que fuera leído como parte de la historia del pensamiento geográfico, gracias a que en las décadas de 1990 y 2000 surgieron varios programas de geografía en el país.</p>
                        <p>En el año 2009 comenzó la última etapa de esta historia, producto de la conformación de un archivo y del montaje de una página web. La base de este proceso fue la creación de un catálogo completo, la digitalización de todas las imágenes y la ubicación del material en la biblioteca Luis Angel Arango (del Banco de la República), con el fin tanto de conservar las fotografías como de facilitar y garantizar su consulta y uso. El paso de estos objetos del cajón de un escritorio en Luisiana a la Sala de Libros Raros y Manuscritos de la mejor biblioteca pública de Colombia cambió radicalmente su significado: dejaron de ser los insumos abandonados de un antiguo proyecto de investigación para convertirse en un archivo –es decir, un repositorio organizado– que hace parte del patrimonio colombiano.</p>

                        <strong>Foto</strong>

                        <p>La creación de la página <a href="http://robertwest.uniandes.edu.co/" target="_blank">(http://robertwest.uniandes.edu.co/)</a> tuvo otros efectos: implicó la publicación de un número mayor de fotografías (321), casi tres veces más que las contenidas en el libro, en un medio, el internet, que permite un acceso potencial mayor que el que ofrecían los libros y con una calidad de reproducción bastante superior. De esta manera, nuevas fotografías vieron la luz pública. Algunas no habían sido escogidas por West para aparecer en el libro porque repetían una característica que otra fotografía mostraba mejor o, al menos, igualmente bien. Pero nosotros tuvimos razones para incluirlas en nuestra muestra: un caserío no es lo mismo que otro, además de que había varias eran sencillamente buenas fotografías. Unas pocas, que llamamos “curiosidades”, no encajaban con los criterios científicos de West; son unos pocos casos en los que parece que él se dio licencia para fotografiar algo que encontró llamativo. Su carácter extraordinario les mereció un lugar en la página. </p>
                        <p>A diferencia de lo que sucede con los libros, en este nuevo formato, a pesar de que hay textos (como este) y pies de fotos, las imágenes pueden desligarse de ellos. El medio, más flexible que una publicación académica, y con el potencial de atraer otro tipo de audiencia, se presta para interpretaciones más libres. Es bien posible, por ejemplo, que algunos vieran una región atrasada en la que más bien poco ha cambiado. Además, buscamos que quien quisiera utilizar las fotografías lo hiciera con la única condición de dar los créditos correspondientes. Esta mayor exposición permitió su circulación en otros ámbitos, entre ellos una especie de exposición permanente en el malecón de Quibdó.</p>
                        <p>La ubicación del archivo en la BLAA llevó a que el Banco de la República tuviera la iniciativa de incluir estas fotografías en una exposición itinerante. La idea original fue de Angela Pérez, directora de la Biblioteca cuando por primera vez fui a hablar de la donación. Pero el apoyo concreto lo dio Margarita Garrido, quien, cuando efectivamente hice la donación, había reemplazado a Angela en la dirección. En la exposición trabajamos Juan Ignacio Arboleda, a cargo de la logística, y Memet Charum, de la estética, por el Banco, y yo, que me encargué del guión. La exposición se inauguró en <b>diciembre</b> de 2011 en Bogotá y viajó en los años siguientes por varias sedes culturales del Banco, entre ellas las de Buenaventura, Cali, Sincelejo, Manizales, Florencia e Ipiales.</p>
                        <p>Esta historia termina, por ahora, con la creación de esta nueva página, un proceso que se desarrolló en 2021 y 2022, y contó con la financiación, igual que la página anterior, de la Facultad de Ciencias Sociales de la Universidad de los Andes. Sin el apoyo institucional de la universidad es posible que las fotos aún estuvieran en un closet, tal vez no en el mío, sino en uno de la BLAA, esperando a que hubiera plata y personal para organizarlas y hacerlas públicas.</p>

                        <strong>Foto</strong>

                        <h3>Tipos raciales</h3>
                        <p>Entre las fotos de West me llaman en particular la atención las que tomó de gente, que son relativamente pocas. Su interés, que nunca ha dejado de parecerme extraño, era captar tipos raciales, a los que consideraba parte del paisaje. Sin embargo, al examinar su perspectiva con más de detalle, se hace más fácil de entender. Para este geógrafo, las personas eran elementos fundamentales de lo que era propio de la región y podía observarse, así como también lo eran los ríos, la vegetación, el tipo de costas, las casas, los poblados, los cultivos, las minas, las canoas y otros artefactos. Pero cumplían un papel doble, no solo eran parte del paisaje, eran sus hacedores; por lo tanto, no los consideraba un elemento más sino el alma que definía el carácter del litoral (para usar una palabra nada propia de West).</p>

                        <strong>Foto</strong>

                        <p>El mejor comienzo para entender las fotografías de la población lo constituyen las que aparecen en el libro. Son tres páginas. La primera incluye tres fotos bajo la etiqueta “Forest indians of the Chocó” (indios de los bosques chocoanos), en las que se destacan sus joyas y vestido (la paruma de las mujeres y la pampanilla de los hombres). En la segunda también hay tres fotos, esta vez de “negroes and mixed-bloods” (negros y mestizos): una de dos jóvenes negros, una de dos mujeres producto de la mezcla entre blanco, negro e indio, y una de dos sambos (mezcla de negro e indio). La última contiene dos fotos de “blancos de la costa al norte de Tumaco”: un pescador-agricultor y un close-up de las caras de muchachas blancas y mulatas.</p>
                        
                        <strong>Foto</strong>

                        <p>Estas son claramente fotos de tipos raciales, que enfatizan las razas originales y las distintas mezclas. Ellas remiten a una larga y problemática tradición que creció al tiempo que se fortalecía el pensamiento racial. Esa tradición se remonta al menos hasta las pinturas de castas de finales del siglo XVIII. Se trata de series, casi todas de la Nueva España (hoy México) y por lo general de 16 cuadros, que muestran las distintas mezclas que se producen de los cruces entre la población de europeos, indígenas y africanos. Los cuadros muestran un padre, una madre y su hijo, con una explicación de cómo se denomina cada uno. En la única serie peruana, encargada por el virrey Amat y Junyent en 1770 para mostrar en Europa las mezclas existentes en la región a su cargo, se incluye, por ejemplo, <b>la pintura que dice “mulata con español producen cuarterón de mulato”.</b> Estas pinturas buscaban restablecer un orden resquebrajado por la mezcla entre grupos que en teoría debían haber permanecido separados: colonizadores, colonizados y africanos esclavizados. </p>
                        <p>La clasificación racial tomó fuerza en el siglo XIX, como lo muestran incontables ejemplos pictóricos, dentro de los cuales se encuentran las acuarelas de tipos regionales racializados de la Comisión Corográfica. Esta comisión, que recorrió y describió a Colombia en la década de 1850, entendía a la población en función de su región y adscripción racial, como lo muestra la acuarela aquí incluida, que ilustra a los tipos blanco, indio y mestizo del área de Tundama en Boyacá. Ya en la segunda mitad del siglo, los europeos aprovecharon el desarrollo de la fotografía para dar cuenta de las culturas que encontraban (y sometían) en sus viajes por el mundo. Estas imágenes fueron una herramienta importante de la etnografía y la antropología, que surgieron de esos encuentros desiguales. Dentro de los usos creados por estas disciplinas está la antropometría que buscaba tener datos cuantitativos que permitieran medir las diferencias entre las razas, y así probar la superioridad de unas frente a otras (sin que fuera una sorpresa cuáles ocupaban cuál lugar). Incluso las tarjetas de visita, antecesoras de las postales, siguieron ese mismo camino, ya en el siglo XX.</p>

                        <strong>Foto</strong>

                        <p>Todos estos ejemplos muestran una larga tradición visual en la que las personas representadas no eran individuos sino ejemplos de tipos raciales, no siempre pero con frecuencia de aquellos grupos poblacionales considerados extraños por quienes producían y consumían dichas imágenes. Las imágenes que antecedieron las fotografías del profesor West fueron parte de un fenómeno de largo aliento que ubicó a la población mundial, o a la de una cierta área, dentro de un orden eurocentrista en el que la raza blanca ocupaba el ápice.</p>
                        <p>Esa tradición recibió un fuerte golpe que minó profundamente su legitimidad con la victoria de los Aliados en la Segunda Guerra Mundial, lo que hace a las fotografías que aquí nos ocupan no solo herederas de una tradición potente sino anacrónicas. Los excesos de los nazis expusieron el peligro de pensar en la diferencia humana en términos raciales, dado que ese marco siempre implica una jerarquía; dicho de otro modo, pensamiento racial y racismo resultan inseparables. El holocausto llevó a que el concepto raza fuera proscrito en círculos oficiales y académicos; además de ser considerado peligroso e indeseable sus bases científicas fueron cuestionadas. Sin embargo, las categorías raciales, afianzadas por décadas de uso, siguieron siendo empleadas en el lenguaje cotidiano. Cambió el lugar donde se utilizaban, pero además el concepto mismo se modificó: tomó preeminencia el aspecto físico sobre el carácter, que había sido tan o más importante en la descripción o construcción de grupos raciales hasta entonces.</p>
                        <p>Estos tres puntos —el rechazo al concepto raza, la persistencia de su uso y la asociación de raza con la fisonomía— ayudan a entender el lugar de las fotografías de tipos raciales en el libro y el pensamiento de Robert C. West.</p>
                        <p>Su anacronismo puede quedar más claro al examinar el caso de los antropólogos que estudiaron a gente negra en Colombia por los mismos años en que West realizó su estudio. Uno de estos ellos, Rafael Arboleda (1952: 199) se preguntaba: «Pero qué llamamos negro? ¿El de piel negra o bronceada?». A lo que responde: «El verdadero criterio para lo que nos importa es cultural. Los pueblos que recibieron la influencia de la inmigración negra durante la conquista, colonia y parte de la independencia, adquirieron una cultura, una semi-cultura negra, visible en muchos rasgos concretos». Arboleda habla de «negro» y sabe que es una categoría racial, y que con el cambio producido por la guerra, raza se asociaba más con la apariencia. Tiene claro también que hablar en términos raciales está mal visto, por eso aclara que lo que le interesa es la cultura. Es decir, usa una categoría racial pero busca tomar distancia con el concepto raza. Arboleda se enfrentaba a un reto casi imposible, porque la tradición y el lenguaje cotidiano estaban en su contra.</p>
                        <p>El tipo de geografía que practicaba West tiene paralelos y diferencias con el caso de los antropólogos. De la misma manera que les sucedía a ellos, aunque West estudia la cultura no puede evadir el concepto raza. En el prefacio del libro West dice que su objetivo es “describir e interpretar la cultura material de una población predominantemente negra”. Podríamos decir que West estudia la cultura material de la raza negra. Pero a diferencia de Arboleda, West acepta el lugar del tema racial en su estudio. Más adelante, en el prefacio afirma lo siguiente:  </p>
                        <p><strong>Debido a que éste es un informe sobre la geografía del área, la sección sobre el medio cultural trata principalmente sobre <i>los elementos materiales que pueden observarse visualmente</i> en campo: <i>las características raciales,</i> los patrones de poblamiento, los tipos de casas, los recursos y las técnicas con que se producen la comida, la ropa, el transporte, etc. Elementos no materiales tales como la organización familiar y comunitaria, la religión, el gobierno, etc., han sido en buena medida excluidos.</strong></p>
                        <p>Su estudio del paisaje, que es una categoría visual, hizo que su aproximación a la cultura fuera material, por lo que el nuevo énfasis en la fisonomía del concepto raza  resultaba acorde con su perspectiva. Por ello, en el capítulo 6, dedicado a la población y al poblamiento, el libro tiene una sección titulada: “composición racial”, que a su vez se divide en “the Indians” (los indios) y “the negroid people” (negros, mulatos y sambos). Por el contario, en antropología el acento en el estudio de la organización social a partir de las décadas de 1920 y 1930 le restó importancia a los documentos visuales, con lo que la fotografía perdió importancia como herramienta en esa disciplina (Edwards). </p>

                        <strong>Foto</strong>

                        <p>West no era el único académico que en la década de 1950 todavía clasificaba a la población en términos raciales. En su primer libro sobre la comunidad de Saucío, Cundinamarca, publicada en inglés, en Estados Unidos, en 1955 y en español, en Colombia, en 1961 como Campesinos de los Andes. Estudio sociológico de Saucío, Orlando Fals Borda, distinguido sociólogo colombiano, incluyó una serie de cuatro fotos del “tipo mestizo”. Pero en sus siguientes libros ya no hay fotografías de tipos raciales. Estas fotografías son los últimos ejemplos de una tradición.</p>

                        <strong>Foto</strong>

                        <p>Las fotografías de West comparten algunos rasgos propios de las imágenes de esta tradición y también tienen sus características propias. Como sus pares, no ocultan su intención, no se excusan. Son posadas, nunca casuales, y en ellas aparece un individuo o un grupo, que a veces mira a la cámara y a veces no. Es posible que esta fuera la primera vez que muchas de estas personas eran retratadas. Con excepción de un par de niños, ellas no muestran emoción de hallarse frente una cámara, aunque tampoco ponen resistencia. A pesar de ser posadas, las fotografías son sencillas y en esa medida no son pretensiosas. West no tomó varias veces la misma escena hasta lograr la expresión o la atmósfera deseada. Supongo que debía hacer buen uso de sus negativos, pues no tenía cómo obtener otros. Además, él se concebía a sí mismo como un geógrafo, no como un fotógrafo que debía lograr la imagen perfecta. Estas fotos escuetas, son también algo frías. La forma en que West fotografió individuos y grupos, asociada a sus pretensiones científicas de retratar lo típico, les imprime una cierta distancia. West no parece interesado en juzgar a los sujetos que observa; al contrario de lo que hicieron muchos etnólogos, no los retrata como rarezas de un mundo desconocido. Sin embargo, los expone de una manera que evoca una colección de piezas de museo.</p>

                        <strong>Foto</strong>

                        <p>Dado que el énfasis es en las personas mismas, el fondo de este tipo de fotografías no suele ser muy relevante. Sin embargo, puede servir de encuadre, como sucede con la hoja de palma en la foto 50B, que realza a la madre y a su hija. Dado que West no era un etnógrafo, es decir, que su interés no era solo la población sino todo el paisaje, en algunas de las fotos combinó personas y entono, como aquella en la que aparecen ocho niños y jóvenes en fila, con una quebrada y una platanera de fondo, que ocupan la mitad del cuadro. Esta combinación de tipos raciales con paisajes que mostraban cómo eran las zonas donde esas personas vivían y trabajaban fue muy usada en las acuarelas de la Comisión, que por ser dibujadas tenían mucha más libertad de composición. Tampoco es novedad que las fotografías de personas que tomó West permiten, en muchos casos, observar elementos de la cultura material a los que puede o no referirse en el texto del libro: principalmente ropa y sombreros, falta de zapatos, y también adornos y herramientas. En una de las fotos seleccionadas para el libro, por ejemplo, aparecen las cachimbas o pipas, destacadas en el pie de foto correspondiente. </p>

                        <strong>Foto</strong>

                        <p>Las fotos que West tomó de personas como tipos raciales evaden otras formas de retratar gente. Su archivo no incluye fotos de personas específicas, con nombre propio, que fueran relevantes en términos de su relación con él o de su estudio. Las imágenes que resultaron de los viajes de exploración al Africa, por ejemplo, según cuenta la historiadora Leila Koivunen, incluyen retratos de gobernantes y otras personas importantes mencionadas en los relatos. En el otro extremo están las imágenes, que también fueron parte del repertorio visual que permitió a los europeos enterarse de sus conquistas en Africa, de festividades y reuniones. El interés de West no era la organización social, así que fotos como las de una fiesta indígena o de un día de mercado, son más bien raras en el archivo fotográfico que nos ocupa. En ellas prima la actividad y no la apariencia de las personas. </p>

                        <strong>Foto</strong>

                        <p>Quisiera terminar esta sección resaltando una diferencia de la mirada de West en relación con la de algunos de sus contemporáneos: él no veía a los pobladores del Pacífico como gente digna de compasión. A diferencia de lo que sucedía con la fotografía documental —practicada tanto en Estados Unidos como en Colombia en la década de 1930 y después— este geógrafo no tenía intención de denuncia. Aunque también buscaba documentar, su pretensión no era mostrar que algo estaba mal sino entender como lo que veía había llegado a ser así. La foto de West en la que aparece un niño panzón lleva la mirada a la mujer que está mineando con su batea en la quebrada; el niño no parece ser el objeto de la imagen. Tampoco trataba de exaltar y embellecer a sus sujetos, como sucedía con algunas de las fotografías de Gerardo Reichel Dolmatoff. </p>

                        <strong>Foto</strong>

                        <p>A pesar de ser un buen fotógrafo, West era modesto. Parecía ignorar o no estar interesado tanto en las tendencias de la fotografía documental de su propia época como en la tradición de la que algunas de sus imágenes hacían parte. El tenía muy claros sus intereses, que daban fuerza para avanzar en sus investigaciones y le evitaban distracciones. El resultado es una curiosa mezcla de anacronismo, desapego y respeto. Ahora sus fotos de gente anónima tienen el potencial de cambiar radicalmente de significado, si quienes aparecen allí retratados, sus hijos o nietos, ven en ellas a personas con nombre y apellido, y tal vez con apodos cariñosos o burlones. Dejarían de ser áridos tipos raciales para convertirse en “don Joaquín” o, mejor, en “mi abuela”; no serían parte de una forma de hacer geografía o de nuestra cultura nacional sino de una familia o de una comunidad. El internet no llega a todos lados, ni todos lo miran, pero es una posibilidad real, que tal vez incluso ya ha sucedido.</p>

                        <h3>Paraíso perdido</h3>
                        <p>Así como las personas retratadas pueden reencarnar en seres queridos con historias propias, el archivo completo, rico y detallado, que ayudó a West a dar una visión panorámica de la región, hoy pasa a ser evidencia de un pasado cada vez más remoto, no del presente del que el autor fue testigo. Estas fotos son una ventana que permite volver décadas atrás para ver la región tal como era. Por un lado, ellas constituyen su mejor registro fotográfico para ese periodo, no sólo por su número, sino también por la gran variedad de lugares y temas fotografiados, y por la calidad de las imágenes. Ahora también por su disponibilidad. Por otro lado, las características miméticas de la fotografía, su (aparente) objetividad y su realismo, facilitan que estas imágenes sean consideradas como una réplica de un tiempo perdido. Fue justamente debido a esa visión de la fotografía como un medio neutral que West la utilizó como herramienta en su estudio científico.</p>
                        <p>Aunque West efectivamente retrató realidades del Pacífico en aquellos años, no podemos ser tan inocentes. Este geógrafo mostró el mundo que observó desde un ángulo específico. Es decir, a pesar de la indisociable relación con su referente, estas fotografías muestran la región de una manera mediada tanto por el fotógrafo como por quien las ve. Hay dos elementos de la mediación de West que propenden por una visión positiva del litoral, que iba en contravía de los aires que se respiraban en la temprana posguerra: un embellecimiento casi involuntario y el énfasis en el adecuado manejo del medio que tenían los pobladores.</p>
                        <p>Susan Sontag nos recuerda que la cámara embellece. Además de documentar la realidad, las fotografías han servido para captar o crear algo hermoso. Aunque las pretensiones de West no eran artísticas, su cámara sí muestra un mundo que tiene encanto. West, como ya he dicho, no se concebía a sí mismo como un fotógrafo y nunca pensó en vender sus fotos o en exponerlas en una galería.  Sin embargo, sí se preocupaba por la calidad de las imágenes que captaba. Como vimos, cargaba dos cámaras, una de ellas de formato mediano. Además, había tomado un curso de fotografía y se esforzaba por lograr una buena composición. La lluvia y nubosidad constantes del litoral debieron haber actuado en contravía de sus pretensiones documentales, pues supongo que en muchos momentos le fue imposible sacar sus cámaras. La falta de sol también debió haber menguado las posibilidades de lograr contrastes. Con todo y eso, produjo cientos de imágenes que sumadas nos muestran una región bella.</p>
                        <p>La imagen más arraigada en los escritos sobre la región de esa época no se centra en sus atractivos, sino en sus carencias. Alfonso Meluk, un destacado político chocoano, escribió en 1954 las siguientes palabras, publicadas en una revista bogotana:</p>
                        <p><strong>Pero, como contraste doloroso, ante este esplendido panorama de riquezas naturales, se alza […] un pueblo en la miseria, con una economía precaria. Azotado por los flagelos del pian, el paludismo y la tuberculosis. Sin higiene. […] Sin industrias. Sin ganadería [..]. Y una explotación agrícola primitiva. Es decir, un pueblo abandonado a su propia suerte (“La tragedia de un pueblo”).</strong></p>
                        <p>West también habla en su libro del pian, una enfermedad tropical causada por una bacteria, y menciona la pobreza. Pero su tono no es de lamento o queja; es más bien una mirada respetuosa, pero no apologética, de las culturas locales, que resultaba, como sus fotografías de tipos raciales, anacrónica. En la era del desarrollo, el llamado era a cambiar, a progresar, no a perder el tiempo escudriñando los modos del atraso. </p>
                        <p>El tinte antimodernista del trabajo de West proviene de su maestro, Carl O. Sauer, quien forjó la Escuela de Berkeley desde los años 30, es decir, antes de la Segunda Guerra Mundial. Los años 50 mostraban ya elementos que serían característicos de las siguientes décadas: el crecimiento económico y el imperativo del desarrollo del llamado Tercer Mundo. En América Latina se construyeron grandes proyectos como hidroeléctricas y se comenzaron a utilizar tecnologías agrícolas modernas –que se conocen bajo el nombre de Revolución Verde. Mientras los científicos trataban de crear variedades mejoradas, el profesor Sauer estudiaba la agricultura de milpa de los campesinos mexicanos y de ese modo valoraba lo que para muchos había que superar.</p>
                        <p>El énfasis de la Escuela de Berkeley en el mundo rural y en las formas de manejo del medio de las comunidades locales guio el trabajo de West. Aunque destacó el atraso económico de la región e incluyó entre los problemas que allí se presentaban “las actitudes y la herencia cultural de los habitantes locales, quienes [habían] tenido pocos incentivos para mejorar su nivel de vida” (p.192), estudió con esmero y describió de manera detallada la agricultura (principalmente de subsistencia pero también comercial), la pesca, la cacería, la minería, haciendo un recuento minucioso de técnicas, tiempos y su relación con suelos, clima y relieve. Y de todas esas actividades productivas hizo un registro gráfico. Este cuidadoso esfuerzo, que le tomó años y le costó más de una fiebre, indicaba que el estudio de la cultura negra (y también de las culturas indígenas) valía la pena.</p>
                        <p>Visiones como la de West son más acordes con la idea del Pacífico como región de gran riqueza cultural que promovieron la Constitución de 1991 y la Ley 70 de 1993. De hecho, el constituyente Orlando Fals Borda utilizó el libro en los debates para aprobar el artículo transitorio 55 de la constitución, como él mismo lo relató en un texto corto:</p>
                        <p><strong>Este artículo [el transitorio 55] fue redactado por mí en pequeño comité, una vez se obtuvo la información básica y el apoyo de las organizaciones negras con las que inicié y mantuve contactos desde el mes de marzo de 1991. Recuerdo que mucho de la resistencia en el seno de la Asamblea se debía a ignorancia sobre la organización social y las formas de poblamiento de la Costa Pacífica, y aquella resistencia se venció en parte cuando llevé y repartí en la Asamblea un precioso mapa detallado del libro de Charles [sic.] C. West, The Pacific Lowlands of Colombia (1950) [sic.].</strong>
                        <br></br><strong>Orlando Fals Borda, “Constituyentes de 1991 también defendimos a los afrocolombianos” América Negra 6, 1993, p.222</strong></p>
                        <p>Así entonces, el libro que en su versión original ayudó al reconocimiento legal de la cultura negra, también vio la luz en español gracias a esa transformación que contribuyó a generar. El parecido entre la mirada de West en la década de 1950 y la promovida por la Constitución de la década de 2000 fue fundamental para impulsar el proceso de recuperación del archivo y creación de esta página. Así habrá nuevos espectadores que aprecien las fotografías desde otros lugares y las llenen de significados novedosos. Es en ese encuentro, entre un objeto, condicionado por su creador y por el medio y contexto que lo hacen visible, y quien lo observa, que este adquiere vida, que su existencia importa. Aquí está entonces este archivo que, como una máquina del tiempo, nos transporta a ese litoral recóndito en la primera mitad de la década de 1950. Después de 20 años de tener cerca estas fotografías, sigo admirándolas y descubriendo cosas nuevas en ellas, espero que lo mismo suceda con el público, cada vez mayor y ojalá de la región misma, que pueda darse el gusto de apreciarlas. </p>


                        </div>    
                    }
                />
            </div>
            <br></br>
            <div className="container mb-5">
                <div className="row">
                    <div className="col-12 col-md-3" >
                    <Cardsection  
                        imagen={ImagenPrueba} 
                        title="CATÁLOGOS"
                        link="catalogos"
                    />
                    </div>
                    <div className="col-12 col-md-3">
                    <Cardsection 
                        imagen={ImagenPrueba2} 
                        title="HISTORIA"
                        link="historia"
                    />
                    </div>
                    <div className="col-12 col-md-3">
                    <Cardsection 
                        imagen={ImagenPrueba3} 
                        title="FOTOGRAFÍAS"
                        link="fotografias"
                    />
                    </div>
                    <div className="col-12 col-md-3">
                    <Cardsection 
                        imagen={ImagenPrueba4} 
                        title="CRÉDITOS"
                        link="creditos"
                    />
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    )
}